name: MidtermResourceFileInclude
version: 1.0.0
summary: Azure Custom Environment including EventHub
description: Functions included
runner: ARM
templatePath: azuredeploy.json
parameters:
  - id: "sites_shimegi_cae_name"
    name: Name of Azure Functions (Ex. cae-functions)
    description: "Ex. cae-functions"
    type: string

  - id: "namespaces_Shimegi_CAE_name"
    name: Name of Eventhub namespace (Ex. Shimegi-CAE)
    description: "Ex. Shimegi-CAE"
    type: string

  - id: "flexibleServers_shimegi_cae_server_name"
    name: Name of PostgreSQL server (Ex. shimegi-cae-server)
    description: "Ex. shimegi-cae-server"
    type: string

  - id: "storageAccounts_cae3shimegi_name" # 変更点
    name: Name of Storage Accounts (Ex. cae1shimegi)
    description: "Ex. cae3shimegi" # 変更点
    type: string

  - id: "vaults_vault_smg0819_name" # 新規追加
    name: Name of the Recovery Services Vault (Ex. vault-smg0819)
    description: "Ex. vault-smg0819"
    type: string

  - id: "serverfarms_ASP_RGSHIMEGICAE_b7eb_name"
    name: Name of config file for Azure Functions (Ex. ASP-RGSHIMEGICAE-962e)
    description: "Ex. ASP_RGSHIMEGICAE_b7eb"
    type: string

  - id: "flexibleServers_admin_name"
    name: Name of admin in PostgreSQL (Ex. watchman)
    description: "Ex. watchman"
    type: string

  - id: "flexibleServers_admin_password"
    name: Name of admin password in PostgreSQL (Ex. password)
    description: "Ex. password"
    required: true
    type: string